#!/usr/bin/env bash
# /pr-review — Steps 0.1, 1, 2 and 4: build the run's artifacts. No model, no judgment.
#
#   usage:  bash .claude/skills/pr-review/scripts/build-artifacts.sh [BASE]
#   env:    PR_REVIEW_NO_GRAPH=1   skip the graphify refresh (tests, CI)
#           PR_REVIEW_PACK=<path>  use another domain pack (tests; a foreign repo's pack)
#           PR_REVIEW_HEAD=<sha>   diff BASE...<sha> instead of BASE...current-HEAD (eval corpus
#                                  reruns against a fixed historical head). patch.diff/manifest.txt
#                                  are always computed against the real repo's objects, but READ_ROOT
#                                  (run.env) points spawned agents at a scoped `git worktree` checked
#                                  out at <sha> instead of the live tree — otherwise a verifier's own
#                                  Read/Grep/Glob calls see whatever the working tree looks like today,
#                                  not the commit under review, and a since-renamed/moved file produces
#                                  a wrong-but-plausible finding (see future-improvements/
#                                  week-5-dirty-tree-stale-citation.md, Direction 2). Reused by SHA
#                                  across repeated reruns of the same historical head, not recreated.
#                                  A dirty working tree (uncommitted changes) gets the same worktree
#                                  treatment automatically, pinned to plain HEAD — see Direction 1 in
#                                  the same file.
#           PR_REVIEW_LARGE_DIFF=<n>  changed-line threshold for the LARGE_DIFF warning (default 2500)
#           PR_REVIEW_KEEP_DAYS=<n>   age in days before a stale pr-review.* run dir, or a stale
#                                  PR_REVIEW_HEAD replay worktree, is pruned (default 7)
#           PR_REVIEW_IMPACTED_CAP=<n>  max impacted-caller candidates to emit (default 24)
#           PR_REVIEW_MATCH_CAP=<n>  max changed-file lines to emit in candidates.txt (default 40; the
#                                  per-file candidate cap is a fixed 3, not this knob)
#           PR_REVIEW_UNIFIED=<n>  diff context width for both patch.diff and code.diff (default 8;
#                                  future-improvements/Applied/week-6-diff-context-width.md's A/B knob —
#                                  moved from 15 after the corpus replay found no recall loss)
#
# Writes into a fresh $OUT under .git/:  patch.diff  manifest.txt  brief.txt  wiring.txt
#   probes-{access,data,answer,structure,all}.txt  known-non-defects.txt
#   impacted-candidates.txt  candidates.txt  records.json  run.env
# Prints run.env (key=value) followed by brief.txt. Exit codes:
#   0 ok (EMPTY=1 in run.env when there is nothing to review)   2 not a git repo
#   3 base does not resolve    4 no merge base (unrelated histories)    5 cannot create $OUT
#   6 cannot create the replay worktree (PR_REVIEW_HEAD, or a dirty tree)
set -u
BASE_ARG="${1:-dev}"
# Resolved from $0, before any cd — this tool's own model/ assets (the
# validator, the record parser, the heading list) live next to this script,
# not in whatever repo is under review. $ROOT below is the reviewed repo and
# is the right base for $PACK's default and everything genuinely
# repo-relative (citations, $OUT under .git/); it is the wrong base for this
# tool's own tooling once this script runs against a foreign repo (week 9's
# design-partner case) — same reasoning model/validate-pack.sh's own
# SCRIPT_DIR already applies, just missing here until now.
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MODEL_DIR="$(cd "$SCRIPT_DIR" && git rev-parse --show-toplevel)/model"
ROOT="$(git rev-parse --show-toplevel 2>/dev/null)" || { echo "error: not inside a git repository" >&2; exit 2; }
cd "$ROOT"
PACK="${PR_REVIEW_PACK:-model/pr-review-domain.md}"

# The Brief probes step below runs `eval "$PROBES"` — arbitrary shell lifted
# straight out of a markdown file. That is a known accepted risk *only while
# the pack's author is the one running it*
# (future-improvements/week-12-remove-brief-probes-eval.md); it becomes
# arbitrary code execution the moment someone runs against a pack they
# didn't write — exactly the partner-pack case
# (`model/partners/<name>/...`, generated by an agent over a codebase
# nobody read) and the phase-3 cold-onboarding test. So: the built-in
# default pack is trusted; a pack handed in via $PR_REVIEW_PACK is trusted
# for `eval` ONLY when the caller has read its Brief probes block and set
# PR_REVIEW_EVAL_BRIEF_PROBES=1 to say so. A non-trusted pack still yields
# a valid brief.txt via the presence-only fallback (same fields as the
# no-pack path). Full removal of `eval` still lands with the week-12 port.
BRIEF_PROBES_TRUSTED=0
if [ -z "${PR_REVIEW_PACK:-}" ] || [ "${PR_REVIEW_EVAL_BRIEF_PROBES:-0}" = 1 ]; then
  BRIEF_PROBES_TRUSTED=1
fi

# ---------- 0.1 domain pack + ledger: existence and path:line staleness,
# batched. One `git ls-files` call across every cited path from both files,
# and one `awk` pass computing line counts for every path with a line
# citation — instead of a spawn pair per citation (up to ~70 subprocesses for
# ~35 citations before batching). Plain newline-delimited strings throughout,
# never bash arrays: this repo's bash is 3.2 (macOS ships it) where
# `"${arr[@]}"` on an *empty* array throws "unbound variable" under `set -u`
# — confirmed, not theoretical — and every list built below can legitimately
# be empty (no pack, no ledger, no line-numbered citations at all).

extract_citations() {  # every `path.ext[:line[-line2]]` citation containing a '/'
  grep -oE '`[A-Za-z0-9_./-]+\.[a-zA-Z]+(:[0-9]+(-[0-9]+)?)?`' "$1" 2>/dev/null | tr -d '`' | grep '/'
}

# missing_pack_headings() — shared with model/validate-pack.sh, not
# duplicated (see model/pack-heading-check.sh for why). $MODEL_DIR, not a
# bare relative path — this file lives in the tool's own repo, not the
# reviewed one.
. "$MODEL_DIR/pack-heading-check.sh"

# The pack's ## Wiring files fenced block, verbatim — shared between
# PACK_WIRING_PATHS (staleness checking, below) and $OUT/wiring.txt (handed
# to every verifier, further down). Was two copy-pasted awk one-liners; a
# fix to one without the other is exactly the duplicated-logic drift
# eval/review-corrections.md already recorded as a real accepted defect.
extract_wiring_block() {
  awk '/^## Wiring files/{f=1;next} /^## /{f=0} f&&/^```/{if(b){exit} b=1;next} f&&b' "$1"
}

PACK_PRESENT=0; STALE=0; PACK_INVALID=0; PACK_CITES=""; PACK_WIRING_PATHS=""
if [ -f "$PACK" ]; then
  PACK_PRESENT=1
  # A section is matched below by its exact `## Heading` string — every
  # extraction downstream (`awk '/^## X/{f=1;next} /^## /{f=0} f'`) degrades
  # to silently empty if that heading is retyped even slightly (a capital
  # letter, an extra space, a rename) and no other check here would notice:
  # PACK_STALE only validates citations *inside* a matched section, so a
  # section matching nothing has no citations to flag as stale either. Catch
  # that directly — exact-match every required heading against the pack
  # before relying on any of the sections below.
  # A missing headings file makes missing_pack_headings() return 1 rather
  # than silently printing nothing — that distinction matters here, or an
  # unreadable list would be indistinguishable from "checked, nothing
  # missing". Missing degrades exactly like a stale/invalid pack (STALE=1,
  # loud warning, generic fallback probes) rather than hard-exiting the
  # whole script — this file's own doctrine everywhere else is "never
  # block a review, degrade instead," and a checkout missing its own
  # tooling asset is the same kind of can't-fully-verify-this-pack state
  # PACK_STALE already exists to represent, not a new class of hard stop.
  if ! MISSING_HEADINGS="$(missing_pack_headings "$MODEL_DIR/pack-headings.txt" "$PACK")"; then
    echo "warning: $MODEL_DIR/pack-headings.txt not found — cannot check required headings; treating pack as stale (generic fallback probes)." >&2
    STALE=1; PACK_INVALID=1
  elif [ -n "$MISSING_HEADINGS" ]; then
    echo "warning: domain pack is missing (or has renamed) these section headings — each degrades silently to empty otherwise: $(printf '%s' "$MISSING_HEADINGS" | tr '\n' '|' | sed 's/|/, /g; s/, $//')" >&2
  fi
  # Only repo-relative citations (containing a '/') are paths. A bare `card_repository.py:59`
  # is shorthand for a full path cited earlier in the same row, and `brief.txt` is an artifact
  # name — checking those against the tree flagged the pack stale on every run.
  PACK_CITES="$(extract_citations "$PACK" | sort -u)"
  # Scoped to inside the fence, same as wiring.txt's own extraction below —
  # scanning the whole section (prose, the fence markers themselves) let a
  # stray placeholder word outside the fence (e.g. "TBD") get treated as a
  # citation, failing path_exists and setting STALE=1 for a pack whose
  # actual wiring paths were fine.
  PACK_WIRING_PATHS="$(extract_wiring_block "$PACK" | grep -E '^[A-Za-z0-9_./-]+$')"
fi

# ---------- 0.1c format validation — wiring-fenced, label field count,
# closed-label membership, brief bash-fence + bash -n, citation
# backtick-wrapping (validate-pack.sh; the heading check above is cheap and
# stays inline, this covers everything it doesn't). An invalid pack is
# treated exactly like a stale one below (STALE=1) rather than refused —
# same doctrine as PACK_STALE: never block a review, degrade to generic
# probes and say so loudly. PACK_INVALID/STALE already initialized above,
# not re-declared here — a missing pack-headings.txt already set both and
# a re-init here would silently discard that. ----------
VALIDATOR="$MODEL_DIR/validate-pack.sh"
if [ "$PACK_PRESENT" = 1 ] && [ -f "$VALIDATOR" ]; then
  VALIDATE_OUT="$(bash "$VALIDATOR" "$PACK" "$ROOT" 2>&1)"
  if [ $? = 1 ]; then
    PACK_INVALID=1; STALE=1
    echo "warning: domain pack fails format validation — treating as stale (empty probes, generic fallback):" >&2
    printf '%s\n' "$VALIDATE_OUT" | sed 's/^/  /' >&2
  fi
fi

# ---------- 0.1b ledger: same path:line staleness, scoped to the section that
# actually reaches an agent (Known non-defects + Label corrections) — a drifted
# citation in Run tally history doesn't feed any prompt, so it isn't checked. ----------
LEDGER="eval/review-corrections.md"
LEDGER_PRESENT=0; LEDGER_STALE=0; LEDGER_CITES=""; KNOWN_NON_DEFECTS_TEXT=""
if [ -f "$LEDGER" ]; then
  LEDGER_PRESENT=1
  KNOWN_NON_DEFECTS_TEXT="$(awk '/^## Known non-defects/{f=1} /^## Run tally/{f=0} f' "$LEDGER")"
  LEDGER_CITES="$(printf '%s\n' "$KNOWN_NON_DEFECTS_TEXT" | extract_citations /dev/stdin | sort -u)"
fi

# ---- batched lookups, built once from every citation collected above ----
ALL_TOKENS="$(printf '%s\n%s\n%s\n' "$PACK_CITES" "$PACK_WIRING_PATHS" "$LEDGER_CITES" | grep -v '^$')"
TRACKED=""
if [ -n "$ALL_TOKENS" ]; then
  TRACKED="$(printf '%s\n' "$ALL_TOKENS" | sed 's/:.*//' | sort -u | xargs git ls-files -- 2>/dev/null)"
fi
path_exists() {
  # Literal-prefix / literal-exact match via awk's index(), not grep's regex
  # — a bare "^$1" or "$1" fed to grep treats any `.`/`*`/etc. in the path as
  # a metacharacter, so two same-shaped paths differing only by a literal
  # dot can cross-match (confirmed: `card_service.py` matched a line for
  # `card_serviceXpy` under the old grep-as-regex version).
  if [ "${1%/}" != "$1" ]; then
    printf '%s\n' "$TRACKED" | awk -v p="$1" 'index($0,p)==1{f=1} END{exit !f}'
  else printf '%s\n' "$TRACKED" | grep -qxF "$1"; fi
}

LINE_COUNTS=""
if [ -n "$ALL_TOKENS" ]; then
  # Only paths confirmed to exist go into the batched awk call below — awk
  # aborts the *entire* multi-file pass on the first unreadable file (tested:
  # every file after it silently loses its count too), so a stale path here
  # must be filtered out first rather than let it poison every path after it.
  EXISTING_LINE_PATHS=""
  while IFS= read -r p; do
    [ -n "$p" ] || continue
    path_exists "$p" && EXISTING_LINE_PATHS="$EXISTING_LINE_PATHS
$p"
  done <<LINE_PATHS_EOF
$(printf '%s\n' "$ALL_TOKENS" | grep ':' | sed 's/:.*//' | sort -u)
LINE_PATHS_EOF
  EXISTING_LINE_PATHS="$(printf '%s\n' "$EXISTING_LINE_PATHS" | grep -v '^$')"
  if [ -n "$EXISTING_LINE_PATHS" ]; then
    LINE_COUNTS="$(printf '%s\n' "$EXISTING_LINE_PATHS" | xargs awk \
      'FNR==1 && NR>1 {print prevfile, prevcount} {prevfile=FILENAME; prevcount=FNR} END{if (prevfile != "") print prevfile, prevcount}' \
      2>/dev/null)"  # one call, every file's count via the FNR==1/NR>1 file-boundary — not gawk's ENDFILE, this repo's awk doesn't have it
  fi
fi
line_count_of() { printf '%s\n' "$LINE_COUNTS" | awk -v p="$1" '$1==p{print $2; exit}'; }

# citation_ok returns 0 (OK) or 1 (STALE) for one `path` or `path:line`/`path:line-line2`
# citation — path existence plus, when a line number is present, a bounds check
# against the file's line count, checking both ends of a range (a start still
# inside a shrunk file with the end now past EOF is still stale). This catches
# a citation pointing past EOF; it does NOT catch a citation pointing at a
# *valid but wrong* line in a file that grew or shrank elsewhere (that needs a
# human/LLM read, same as any other content check) — bounds, not semantics.
citation_ok() {
  path="$1"; line=""; end_line=""
  case "$1" in
    */*:*)
      path="${1%%:*}"; linespec="${1#*:}"; line="${linespec%%-*}"
      case "$linespec" in *-*) end_line="${linespec#*-}";; *) end_line="$line";; esac
      ;;
  esac
  path_exists "$path" || return 1
  if [ -n "$line" ]; then
    case "$line" in ''|*[!0-9]*) return 0;; esac
    case "$end_line" in ''|*[!0-9]*) return 0;; esac
    n="$(line_count_of "$path")"
    [ -n "$n" ] && [ "$line" -ge 1 ] && [ "$end_line" -ge "$line" ] && [ "$end_line" -le "$n" ]
  fi
}

if [ "$PACK_PRESENT" = 1 ]; then
  while IFS= read -r c; do
    [ -n "$c" ] || continue
    citation_ok "$c" || STALE=1
  done <<PACK_CITES_EOF
$(printf '%s\n%s\n' "$PACK_CITES" "$PACK_WIRING_PATHS")
PACK_CITES_EOF
  [ "$STALE" = 1 ] && echo "note: domain pack cites a path or line that no longer matches this repo — treating as stale." >&2
fi

if [ "$LEDGER_PRESENT" = 1 ]; then
  while IFS= read -r c; do
    [ -n "$c" ] || continue
    citation_ok "$c" || LEDGER_STALE=1
  done <<LEDGER_CITES_EOF
$LEDGER_CITES
LEDGER_CITES_EOF
  # Warn only — never gate on this. A drifted line number inside one rule's
  # supporting citation doesn't invalidate the rule (the rule is the prose,
  # the citation is evidence for it), and unlike the pack — where staleness
  # falls back to generic probes, a safe degrade — emptying the whole
  # known-non-defects corpus over one bad citation would silently un-suppress
  # every other rule's false positive, the opposite of what this file is for.
  [ "$LEDGER_STALE" = 1 ] && echo "warning: ledger's Known non-defects/Label corrections cite a path or line that no longer matches this repo — a citation has drifted, go fix it (still passed to the scout: gating on this would drop every other rule too)." >&2
fi

# ---------- 1.1 base ----------
if git rev-parse --verify --quiet "$BASE_ARG" >/dev/null; then
  BASE="$BASE_ARG"; BASE_NOTE=""
  # local branch resolved — check it against origin's copy (no fetch: whatever origin/* the
  # last fetch left behind) so a stale local base doesn't silently review against old history.
  if git rev-parse --verify --quiet "origin/$BASE_ARG" >/dev/null; then
    LOCAL_SHA="$(git rev-parse "$BASE_ARG")"; ORIGIN_SHA="$(git rev-parse "origin/$BASE_ARG")"
    if [ "$LOCAL_SHA" != "$ORIGIN_SHA" ]; then
      if git merge-base --is-ancestor "$ORIGIN_SHA" "$LOCAL_SHA" 2>/dev/null; then
        BASE_NOTE="local $BASE_ARG is ahead of origin/$BASE_ARG (unpushed commits)"
      elif git merge-base --is-ancestor "$LOCAL_SHA" "$ORIGIN_SHA" 2>/dev/null; then
        BASE_NOTE="local $BASE_ARG is behind origin/$BASE_ARG — run 'git pull' or 'git fetch' before reviewing"
      else
        BASE_NOTE="local $BASE_ARG and origin/$BASE_ARG have diverged — run 'git pull' or 'git fetch' before reviewing"
      fi
      echo "warning: $BASE_NOTE" >&2
    fi
  fi
elif git rev-parse --verify --quiet "origin/$BASE_ARG" >/dev/null; then BASE="origin/$BASE_ARG"; BASE_NOTE="only origin/$BASE_ARG resolved — reviewing against it"
else echo "error: base '$BASE_ARG' resolves neither locally nor as origin/$BASE_ARG. Not substituting another base." >&2; exit 3; fi
HEAD_REF="${PR_REVIEW_HEAD:-HEAD}"
git rev-parse --verify --quiet "$HEAD_REF" >/dev/null || { echo "error: PR_REVIEW_HEAD '$HEAD_REF' does not resolve." >&2; exit 3; }
git merge-base "$BASE" "$HEAD_REF" >/dev/null 2>&1 || { echo "error: no merge base between $BASE and $HEAD_REF (unrelated histories)." >&2; exit 4; }
HEAD_SHA="$(git rev-parse "$HEAD_REF")"
if [ "$HEAD_REF" = HEAD ]; then
  git symbolic-ref -q HEAD >/dev/null || BASE_NOTE="${BASE_NOTE:+$BASE_NOTE; }HEAD is detached"
fi

# ---------- 1.3a dirty tree (moved ahead of READ_ROOT — it now decides READ_ROOT too) ----------
DIRTY=0; git status --porcelain | grep -q . && DIRTY=1

# ---------- 1.3b READ_ROOT — where spawned agents read source files from ----------
# Diverges from $ROOT for a PR_REVIEW_HEAD replay *or* a dirty tree: patch.diff/
# manifest.txt above are computed via `git diff`, which reads git objects and is
# correct for any commit pair regardless of working-tree state. A verifier's own
# Read/Grep/Glob calls are not — they see the live filesystem at $ROOT, which
# drifts from the diffed commit two ways: (a) a historical HEAD_SHA the moment
# anything has been renamed, moved or restructured since (this repo's own
# core/harness split did exactly that to two week-2 corpus entries), and (b) a
# dirty $ROOT, where uncommitted edits on disk are invisible to `git diff
# BASE...HEAD` but visible to a live Read — a verifier can then cite the
# uncommitted version of a line while reporting it as part of the reviewed diff,
# or miss a defect the diff still shows because disk already fixed it (see
# future-improvements/week-5-dirty-tree-stale-citation.md, Directions 1 and 2).
# Both cases get the same fix: read via a detached worktree pinned to the exact
# commit the diff is against, never the live tree. Named by SHA and reused, not
# recreated, so replaying the same head twice (the normal eval case, and a
# second dirty-tree run before any new commit) costs one checkout, not one per
# run.
KEEP_DAYS_WT="${PR_REVIEW_KEEP_DAYS:-7}"
WT_PREFIX="pr-review-replay-$(basename "$ROOT")-"
find "${TMPDIR:-/tmp}" -maxdepth 1 -type d -name "${WT_PREFIX}*" -mtime "+$KEEP_DAYS_WT" 2>/dev/null \
  | while IFS= read -r stale; do
      [ -n "$stale" ] || continue
      git worktree remove --force "$stale" 2>/dev/null || rm -rf "$stale"
    done
git worktree prune 2>/dev/null || true
if [ -n "${PR_REVIEW_HEAD:-}" ] || [ "$DIRTY" = 1 ]; then
  READ_ROOT="${TMPDIR:-/tmp}/${WT_PREFIX}${HEAD_SHA}"
  if [ ! -d "$READ_ROOT" ]; then
    git worktree add --detach "$READ_ROOT" "$HEAD_SHA" >/dev/null 2>&1 \
      || { echo "error: cannot create replay worktree at $READ_ROOT for $HEAD_SHA" >&2; exit 6; }
  fi
else
  READ_ROOT="$ROOT"
fi

# ---------- 1.4 excludes ----------
# *.lock already covers yarn.lock/Cargo.lock/Pipfile.lock/composer.lock (they
# all end in ".lock") — pnpm-lock.yaml and go.sum don't, so this repo's own
# npm lockfile isn't the only lockfile shape a foreign repo running this same
# pack (SKILL.md's own portability story) could hit.
EXCLUDES=(
  ':(exclude)**/*.lock' ':(exclude)**/package-lock.json' ':(exclude)**/pnpm-lock.yaml'
  ':(exclude)**/go.sum' ':(exclude)**/*.snap'
  ':(exclude)**/dist/**' ':(exclude)**/build/**' ':(exclude)**/*.min.*' ':(exclude)**/*.rdb'
  ':(exclude)**/*.png' ':(exclude)**/*.jpg' ':(exclude)**/*.jpeg' ':(exclude)**/*.gif'
  ':(exclude)**/*.ico' ':(exclude)**/*.pdf' ':(exclude)**/*.woff*'
)

# ---------- 1.5 artifacts, run-scoped ----------
GIT_DIR="$(git rev-parse --git-dir)"
# Prune old run dirs from past reviews — mktemp -d never cleans up after
# itself, and these accumulate forever otherwise. Only the dotted glob
# (past run dirs); .git/pr-review/ (no dot) is the fixed findings.json path
# /explain-bug reads and is never touched here.
KEEP_DAYS="${PR_REVIEW_KEEP_DAYS:-7}"
find "$GIT_DIR" -maxdepth 1 -type d -name 'pr-review.*' -mtime "+$KEEP_DAYS" -exec rm -rf {} + 2>/dev/null
OUT="$(mktemp -d "$GIT_DIR/pr-review.XXXXXX")" || { echo "error: cannot create run directory under .git/" >&2; exit 5; }
OUT="$(cd "$OUT" && pwd)"
UNIFIED="${PR_REVIEW_UNIFIED:-8}"
git diff "--unified=$UNIFIED" "$BASE...$HEAD_REF" -- . "${EXCLUDES[@]}" > "$OUT/patch.diff"   || { echo "error: cannot write patch.diff" >&2; exit 5; }
git diff --name-only  "$BASE...$HEAD_REF" -- . "${EXCLUDES[@]}" > "$OUT/manifest.txt" || { echo "error: cannot write manifest.txt" >&2; exit 5; }
CHANGED=$(git diff --numstat "$BASE...$HEAD_REF" -- . "${EXCLUDES[@]}" | awk '{a+=$1; d+=$2} END {print a+d+0}')
FILES=$(grep -c . "$OUT/manifest.txt")
RAW_FILES=$(git diff --name-only "$BASE...$HEAD_REF" | grep -c .)

# ---------- 1.5b large-diff warning (no trim — a warning costs nothing extra,
# and a silent trim would change recall no one asked to change) ----------
LARGE_DIFF_THRESHOLD="${PR_REVIEW_LARGE_DIFF:-2500}"
LARGE_DIFF=0
if [ "$CHANGED" -gt "$LARGE_DIFF_THRESHOLD" ]; then
  LARGE_DIFF=1
  echo "warning: $CHANGED changed lines across $FILES files, above the ${LARGE_DIFF_THRESHOLD}-line guideline — all five spawns (scout + 4 verifiers) each read the full patch at 15 lines of context; consider a narrower review or splitting the PR." >&2
fi

# ---------- 1.6 empty diff ----------
EMPTY=0
if [ "$CHANGED" -eq 0 ]; then
  EMPTY=1
  if [ "$RAW_FILES" -gt 0 ]; then echo "Nothing to review: every changed file was excluded (lockfiles/binaries/build output). $RAW_FILES file(s) swallowed." >&2
  else echo "Nothing to review: HEAD matches $BASE (after exclusions)." >&2; fi
fi

# ---------- 1.7 dirty tree — computed in 1.3a, above, since READ_ROOT needs it ----------

# ---------- 1.8 graph refresh ----------
# No more precompute/paste here: pr-review-scout and the pr-verify-* agents hold
# live graphify MCP tools (get_node/get_neighbors/query_graph/shortest_path,
# registered in .mcp.json) and call the graph themselves, per file, as needed.
# This step only keeps graph.json fresh before they do.
GRAPH=off
if [ "$EMPTY" = 0 ] && [ -f graphify-out/graph.json ] && [ "${PR_REVIEW_NO_GRAPH:-0}" != 1 ]; then
  if command -v graphify >/dev/null 2>&1 && graphify update . >/dev/null 2>&1; then
    GRAPH=on
  else echo "note: 'graphify update' unavailable/failed — graph off." >&2; fi
fi

# ---------- 1.9 impacted callers — candidate list, graph-independent ----------
# Unchanged files that reference something this diff changed. The scout used to
# resolve these only from graphify's incoming edges, which made `impacted` empty
# on every repo without a graph — i.e. every new adopter, and the check is most
# valuable exactly there. This computes candidates deterministically instead, so
# `impacted` is populated on both paths: graph-on adds precision (real edges,
# symbol-level), graph-off still gets a real list rather than nothing.
#
# Deliberately a *candidate* list, not an answer. A word-boundary reference is
# not proof of a call — the scout confirms each one against the file and drops
# what doesn't hold, exactly as it does with a grep-resolved `related`.
#
# Format: one `caller<TAB>changed-file` per line. Caps are what keep this
# "one cheap pass": at most PROBE_CAP changed files probed, PER_FILE_CAP callers
# each, IMPACTED_CAP total, and each caller path appears once.
IMPACTED_CAP="${PR_REVIEW_IMPACTED_CAP:-24}"
IMPACTED_PER_FILE_CAP=3
IMPACTED_PROBE_CAP=60
: > "$OUT/impacted-candidates.txt"
IMPACTED_TRUNCATED=0
IMPACTED_SEEN=""
if [ "$EMPTY" = 0 ]; then
  probed=0; emitted=0
  while IFS= read -r changed; do
    [ -n "$changed" ] || continue
    [ "$emitted" -ge "$IMPACTED_CAP" ] && { IMPACTED_TRUNCATED=1; break; }
    if [ "$probed" -ge "$IMPACTED_PROBE_CAP" ]; then IMPACTED_TRUNCATED=1; break; fi
    # Non-code files have no callers to break; a data/config file's name is also
    # the token most likely to false-match prose.
    case "$changed" in
      *.md|*.txt|*.rst|*.json|*.yaml|*.yml|*.toml|*.ini|*.cfg|*.env|*.lock|*.snap|*.csv|*.sql) continue ;;
    esac
    tok="${changed##*/}"; tok="${tok%.*}"
    # A token this generic matches most of the repo, so every hit is noise.
    case "$tok" in
      __init__|__main__|index|main|app|application|utils|util|types|type|const|constants|helpers|helper|config|conf|settings|setup|test|tests|spec|mod|lib|base|core|common) continue ;;
    esac
    [ "${#tok}" -ge 4 ] || continue
    probed=$((probed+1))
    n=0
    while IFS= read -r caller; do
      [ -n "$caller" ] || continue
      # Already in the diff: covered by the patch itself, not an impacted caller.
      grep -qxF "$caller" "$OUT/manifest.txt" && continue
      printf '%s\n' "$IMPACTED_SEEN" | grep -qxF "$caller" && continue
      IMPACTED_SEEN="$IMPACTED_SEEN
$caller"
      printf '%s\t%s\n' "$caller" "$changed" >> "$OUT/impacted-candidates.txt"
      n=$((n+1)); emitted=$((emitted+1))
      # Per-file cap counts as truncation too — the list is not exhaustive, and
      # a run that silently showed 3 of 30 callers would read as "only 3 exist".
      [ "$n" -ge "$IMPACTED_PER_FILE_CAP" ] && { IMPACTED_TRUNCATED=1; break; }
      [ "$emitted" -ge "$IMPACTED_CAP" ] && break
    done <<IMPACTED_EOF
$(git grep -lwF "$tok" "$HEAD_SHA" -- . "${EXCLUDES[@]}" 2>/dev/null | sed 's|^[^:]*:||')
IMPACTED_EOF
  done < "$OUT/manifest.txt"
fi
IMPACTED_CANDIDATES=$(grep -c . "$OUT/impacted-candidates.txt" 2>/dev/null || true)
IMPACTED_CANDIDATES="${IMPACTED_CANDIDATES:-0}"

# ---------- 2 stack scope (path-prefix test) ----------
BACKEND_PREFIX='^Backend/'; FRONTEND_PREFIX='^Frontend/'; CODE_DIRS=()
if [ "$PACK_PRESENT" = 1 ]; then
  STACK_SCOPE_SECTION="$(awk '/^## Stack scope prefixes/{f=1;next} /^## /{f=0} f' "$PACK")"
  # model/FORMAT.md §1b's single-stack line — a repo with nothing to split
  # has no table row to give, so this is the only way it can make BE/FE
  # resolve at all. `.` matches any non-empty manifest line: the pack is
  # declaring "every changed file is this one stack," not naming a prefix.
  SINGLE_STACK="$(printf '%s\n' "$STACK_SCOPE_SECTION" | grep -oE '^single-stack:[[:space:]]*(backend|frontend)[[:space:]]*$' | awk -F: '{gsub(/ /,"",$2); print $2}')"
  case "$SINGLE_STACK" in
    backend)  BACKEND_PREFIX='.' ;;
    frontend) FRONTEND_PREFIX='.' ;;
  esac
  # first backtick token of each row in the "## Stack scope prefixes" table, paired with its stack
  while IFS='|' read -r _ pre stack _; do
    pre="$(printf '%s' "$pre" | grep -oE '`[^`]+`' | head -1 | tr -d '`')"; stack="$(printf '%s' "$stack" | tr -d ' ')"
    [ -z "$pre" ] && continue
    case "$stack" in backend) BACKEND_PREFIX="^$pre";; frontend) FRONTEND_PREFIX="^$pre";; esac
    CODE_DIRS+=("$pre")
  done < <(printf '%s\n' "$STACK_SCOPE_SECTION" | grep -E '^\|' | grep -vE '^\|[- |]+\|$' | grep -v 'Prefix')
  # model/FORMAT.md §1b: neither shape resolved (empty section or
  # unparseable prose, same failure either way) — the silent degrade to
  # the hardcoded ^Backend//^Frontend/ defaults, which match this repo's
  # manifest by coincidence or not at all. validate-pack.sh fails this
  # outright (§1b: invalid, not merely stale); this warns independently
  # of that verdict, since BE/FE resolution here runs whether or not the
  # pack otherwise validated clean.
  if [ -z "$SINGLE_STACK" ] && [ "${#CODE_DIRS[@]}" -eq 0 ]; then
    echo "warning: domain pack's '## Stack scope prefixes' section has no parseable table row or single-stack: line (model/FORMAT.md §1b) — BE/FE fall back to the hardcoded Backend//Frontend/ defaults, which may not match this repo at all" >&2
  fi
fi
CODE_DIRS_IS_MANIFEST=0
if [ "${#CODE_DIRS[@]}" -eq 0 ]; then
  # no pack: every top-level directory the manifest touches
  while IFS= read -r d; do CODE_DIRS+=("$d/"); done < <(grep '/' "$OUT/manifest.txt" | cut -d/ -f1 | sort -u)
  # This list is exhaustive over the manifest — and code.diff below reuses
  # patch.diff verbatim instead of re-diffing — only when every changed path
  # actually sits in a subdirectory. A bare top-level file (no '/') has no
  # entry in CODE_DIRS at all, so if one exists this shortcut must not fire:
  # that file's diff would silently vanish from code.diff.
  grep -qv '/' "$OUT/manifest.txt" || CODE_DIRS_IS_MANIFEST=1
fi
grep -qE "$BACKEND_PREFIX"  "$OUT/manifest.txt" && BE=1 || BE=0
grep -qE "$FRONTEND_PREFIX" "$OUT/manifest.txt" && FE=1 || FE=0
if   [ "$BE" = 1 ] && [ "$FE" = 1 ]; then SCOPE=both
elif [ "$BE" = 1 ];                  then SCOPE=backend
elif [ "$FE" = 1 ];                  then SCOPE=frontend
else                                      SCOPE=neither; fi

# ---------- 4 orientation brief — facts only, grep/awk only ----------
BRIEF="$OUT/brief.txt"
if [ "$CODE_DIRS_IS_MANIFEST" = 1 ]; then
  # CODE_DIRS is exactly the manifest's own top-level dirs with no bare
  # top-level file outside them — a diff scoped to them is byte-identical to
  # patch.diff already built above. Reuse it instead of a second full
  # `git diff` traversal over the same range.
  cp "$OUT/patch.diff" "$OUT/code.diff"
elif [ "${#CODE_DIRS[@]}" -gt 0 ]; then
  git diff "--unified=$UNIFIED" "$BASE...$HEAD_REF" -- "${CODE_DIRS[@]}" "${EXCLUDES[@]}" > "$OUT/code.diff"
else : > "$OUT/code.diff"; fi
added() { grep '^+' "$OUT/code.diff" | grep -v '^+++'; }
# Deleted lines matter as much as added ones — a probe over added() alone is
# blind to a removed guard (an ownership filter, a lock call, an await), which
# reads as "nothing here" instead of "something was taken out." In scope for
# the pack's own probes below, same as added().
removed() { grep '^-' "$OUT/code.diff" | grep -v '^---'; }
BRIEF_DEGRADED=0
{
  echo "scope:                  $SCOPE"
  echo "changed lines:          $CHANGED"
  echo "files:                  $FILES"
  if [ "$PACK_PRESENT" = 1 ] && [ "$STALE" = 0 ] && [ "$BRIEF_PROBES_TRUSTED" = 1 ]; then
    # the pack's own probes, verbatim, run in a subshell with added(), removed() and $OUT in scope
    PROBES="$(extract_brief_probes_block "$PACK")"
    # D3 fix: stderr used to go straight to /dev/null — a broken probe block
    # (bad quoting, an undefined command) failed silently mid-brief with no
    # trace anywhere. Captured to $OUT/brief-probes-stderr instead; non-empty
    # means the block errored, so flag it rather than let brief.txt look
    # complete when a field silently never got written.
    ( eval "$PROBES"; echo "router registered:      ${ROUTERS:-none}" ) 2>"$OUT/brief-probes-stderr"
    if [ -s "$OUT/brief-probes-stderr" ]; then
      BRIEF_DEGRADED=1
      echo "note: domain pack's Brief probes block raised an error — brief.txt may be missing whatever it would have added: $(head -1 "$OUT/brief-probes-stderr")" >&2
    fi
  else
    # Presence-only fallback: no pack, a stale pack, OR a pack whose Brief
    # probes block was not trusted for `eval` (see BRIEF_PROBES_TRUSTED
    # above). The last case is a deliberate safe degrade for the partner /
    # cold-onboarding path, not a failure — say so in brief.txt so the
    # missing pack-specific fields don't read as "nothing matched."
    if [ "$PACK_PRESENT" = 1 ] && [ "$STALE" = 0 ] && [ "$BRIEF_PROBES_TRUSTED" != 1 ]; then
      echo "note:                   Brief probes not run — pack came via \$PR_REVIEW_PACK and its shell block was not trusted for eval (set PR_REVIEW_EVAL_BRIEF_PROBES=1 only after reading that block)"
    fi
    echo "migrations:             $(grep -c 'migrations/\|/versions/' "$OUT/manifest.txt")"
    echo "lockfiles/deps touched: $(grep -cE 'package\.json$|requirements\.txt$|pyproject\.toml$|go\.mod$|Cargo\.toml$' "$OUT/manifest.txt")"
  fi
} > "$BRIEF"

# ---------- wiring files, verbatim from the pack (empty file when absent or
# stale — same gate as probes-*.txt below; wiring.txt used to skip the STALE
# check, so an invalid/stale pack could still hand every verifier a
# pre-cleared file list, contradicting the documented safe-degrade). ----------
if [ "$PACK_PRESENT" = 1 ] && [ "$STALE" = 0 ]; then
  # D1 fix: reset f at the *next heading*, not only at the next fence — an
  # unclosed fence used to make this scan straight past "## Wiring files"
  # into whatever section followed, up to that section's own fence.
  extract_wiring_block "$PACK" > "$OUT/wiring.txt"
else : > "$OUT/wiring.txt"; fi

# ---------- per-slice label probes, split once here instead of 4 spawns each reading
# the whole pack (empty files when absent/stale — verifiers already carry their own
# fallback prose for that case, same signal as an empty wiring.txt). Week 3: the
# section holds N convention records (### id, key: value fields), not table rows —
# multi-line field values (a wrapped statement, a multi-entry witnesses list) are
# why this is python3, not another awk one-liner (model/parse_conventions.py's own
# header: ~30 lines of hand-rolled parsing is the line, and continuation lines cross
# it). A record with an unmatched label warns on stderr and is dropped, never blocks
# — same doctrine as every other pack degrade. ----------
# python3 backs both parse_conventions.py calls below (this render, and the
# Promoted non-defects extraction further down) — probed once here, not per
# call site.
HAVE_PY3=0
command -v python3 >/dev/null 2>&1 && HAVE_PY3=1

for f in access data answer structure; do : > "$OUT/probes-$f.txt"; done
echo '[]' > "$OUT/records.json"
if [ "$PACK_PRESENT" = 1 ] && [ "$STALE" = 0 ]; then
  if [ "$HAVE_PY3" = 1 ]; then
    python3 "$MODEL_DIR/parse_conventions.py" "$PACK" render "$OUT" "$BE" "$FE"
    # ---------- records.json (week 7): one {id, label, exemplar, guard,
    # unsafe_when, stack} per stack-allowed record, keyed by id — what the
    # workflow script looks up to render a "governed units" block for a
    # governed·strong file, since probes-*.txt is label-indexed prose, not
    # a per-record lookup. ----------
    python3 "$MODEL_DIR/parse_conventions.py" "$PACK" records-json "$BE" "$FE" > "$OUT/records.json"
  else
    echo "warning: python3 not found — Label probes records not rendered, probes-*.txt/records.json left empty" >&2
  fi
fi

# ---------- candidates.txt (week 6): the deterministic pre-pass. Every
# record is scored per changed file on four structural signals derived from
# its own exemplar/witnesses/guard (model/FORMAT.md §3c) — no author-set
# field. A score >= 3 is a cheap, over-inclusive candidate, never a verdict;
# the scout still confirms (governed) or rejects it (new). Same gate as
# probes-*.txt (no pack, or stale, means no candidates — a safe degrade, not
# a crash), same cap philosophy as impacted-candidates.txt above.
# READ_ROOT, not ROOT — the symbol signal reads the exemplar's file, and on
# a PR_REVIEW_HEAD replay or a dirty tree that must be the tree the diff was
# computed against, same reasoning as every other READ_ROOT use here. ----------
# MATCH_CAP below limits total lines in candidates.txt, i.e. how many
# changed files get a line at all on a very wide diff — it does NOT limit
# candidates within one file, which is a fixed cap of 3 inside
# parse_conventions.py's own match() (model/FORMAT.md §3c).
MATCH_CAP="${PR_REVIEW_MATCH_CAP:-40}"
: > "$OUT/candidates.txt"
if [ "$PACK_PRESENT" = 1 ] && [ "$STALE" = 0 ] && [ "$HAVE_PY3" = 1 ]; then
  python3 "$MODEL_DIR/parse_conventions.py" "$PACK" match "$OUT/patch.diff" "$READ_ROOT" "$BE" "$FE" \
    | head -n "$MATCH_CAP" > "$OUT/candidates.txt"
fi
# One line per changed file always ("(none)" included) — count only the
# ones carrying a real candidate, not every changed file.
CANDIDATES=$(awk -F'\t' '$2 != "(none)"' "$OUT/candidates.txt" 2>/dev/null | grep -c . || true)
CANDIDATES="${CANDIDATES:-0}"

# ---------- scout gets every label's probes in one file — it has no slice
# restriction (unlike the four verifiers), so it needs the union, not a split.
# Built from the four files above, not re-parsed from the pack. Concatenated
# BEFORE the Dependencies append below, so that block lands once per file
# rather than four times over in this one. ----------
cat "$OUT/probes-access.txt" "$OUT/probes-data.txt" "$OUT/probes-answer.txt" "$OUT/probes-structure.txt" > "$OUT/probes-all.txt" 2>/dev/null

# ---------- the pack's ## Dependencies list, appended to every slice's probes
# and to the scout's union, and so to every spawn's prompt. Not its own
# artifact/payload field: no label owns it — any of the 15 can hit the "is this
# import new?" question, and the rule it carries (check the manifest before
# calling a dependency newly-added) is a false-positive guard, not a probe for
# one defect shape. Appending here is what makes it reachable at all: no agent
# may open the pack itself, so a pack section landing in no probes-*.txt lands
# in no prompt. ----------
if [ "$PACK_PRESENT" = 1 ] && [ "$STALE" = 0 ]; then
  DEPS_TEXT="$(awk '/^## Dependencies/{f=1;next} /^## /{f=0} f' "$PACK" | grep -v '^$')"
  if [ -n "$DEPS_TEXT" ]; then
    # Deliberately NOT formatted as "`name` — text" like the label rows above.
    # That shape is what an agent reads as "here is another label", and a
    # hypothesis or finding carrying a label outside the closed 15 is dropped
    # silently by the workflow (labelToSlice lookup misses -> droppedHypotheses),
    # so a row that merely looks like a label can cost a real finding.
    for f in access data answer structure all; do
      printf '\nIN-BOUNDS DEPENDENCIES (reference, not a label — never report a finding under this name):\n%s\n' "$DEPS_TEXT" >> "$OUT/probes-$f.txt"
    done
  fi
fi

# ---------- known non-defects, scout-only — two producers into one consumer.
# The ledger's "Known non-defects" and "Label corrections" sections (extracted
# in 0.1b above, along with the staleness check on the citations in them),
# never "Run tally" onward — that tail grows every verdicted run, scout needs
# the evergreen rules, not the run history. And now the pack's own
# "## Promoted non-defects" (week 3, Thursday) — rules a human watched come
# back twice on *this* repo, promoted out of the ledger the same file section
# above is extracted from, formerly hardcoded straight into
# core/agents/scout.md (a rule that only matched one particular codebase,
# with nowhere else to live). Ledger first, then pack — order doesn't matter
# to the scout (neither is positional), but keeps this file's own history
# ahead of what's freshest. Empty when neither is present, or both sections
# exist with nothing under them. Not gated on staleness for either producer —
# same reasoning as the ledger's own half: one drifted citation shouldn't
# suppress every other rule. ----------
PACK_NON_DEFECTS_TEXT=""
if [ "$PACK_PRESENT" = 1 ] && [ "$HAVE_PY3" = 1 ]; then
  PACK_NON_DEFECTS_TEXT="$(python3 "$MODEL_DIR/parse_conventions.py" "$PACK" extract-section "## Promoted non-defects" | grep -v '^$')"
fi
if { [ "$LEDGER_PRESENT" = 1 ] && [ -n "$KNOWN_NON_DEFECTS_TEXT" ]; } || [ -n "$PACK_NON_DEFECTS_TEXT" ]; then
  # -n guards a section that matched but was empty (e.g. a ledger with a
  # "## Known non-defects" heading and nothing under it before "## Run tally")
  # — printf '%s\n' on an empty string still writes one newline, a 1-byte file
  # that reads as truthy in JS (pr-review-verify.js's `probesAllText ? ... : ...`
  # pattern) though there is nothing in it to show the scout.
  {
    [ -n "$KNOWN_NON_DEFECTS_TEXT" ] && printf '%s\n' "$KNOWN_NON_DEFECTS_TEXT"
    [ -n "$PACK_NON_DEFECTS_TEXT" ] && printf '%s\n' "$PACK_NON_DEFECTS_TEXT"
  } > "$OUT/known-non-defects.txt"
else
  : > "$OUT/known-non-defects.txt"
fi

# ---------- run.env ----------
{
  echo "OUT=$OUT"; echo "REPO_ROOT=$ROOT"; echo "READ_ROOT=$READ_ROOT"; echo "BASE=$BASE"; echo "HEAD=$HEAD_SHA"
  echo "SCOPE=$SCOPE"; echo "BE=$BE"; echo "FE=$FE"; echo "GRAPH=$GRAPH"
  echo "CHANGED=$CHANGED"; echo "FILES=$FILES"; echo "EMPTY=$EMPTY"; echo "DIRTY=$DIRTY"; echo "LARGE_DIFF=$LARGE_DIFF"
  echo "IMPACTED_CANDIDATES=$IMPACTED_CANDIDATES"; echo "IMPACTED_TRUNCATED=$IMPACTED_TRUNCATED"
  echo "CANDIDATES=$CANDIDATES"
  echo "PACK_PRESENT=$PACK_PRESENT"; echo "PACK_STALE=$STALE"; echo "PACK_INVALID=$PACK_INVALID"
  echo "LEDGER_PRESENT=$LEDGER_PRESENT"; echo "LEDGER_STALE=$LEDGER_STALE"; echo "BASE_NOTE=$BASE_NOTE"
  echo "BRIEF_DEGRADED=$BRIEF_DEGRADED"; echo "BRIEF_PROBES_TRUSTED=$BRIEF_PROBES_TRUSTED"
} > "$OUT/run.env"
cat "$OUT/run.env"; echo "--- brief.txt ---"; cat "$BRIEF"
[ "$DIRTY" = 1 ] && echo "note: uncommitted changes are not in this diff." >&2
exit 0
